[plugins]
paperweight = { id = "io.papermc.paperweight.userdev", version.ref = "paperweight" }
runPaper = { id = "xyz.jpenilla.run-paper", version.ref = "runPaper" }
shadow = { id = "io.github.goooler.shadow", version.ref = "shadow" }

[versions]
# Paper
paper = "1.21.1-R0.1-SNAPSHOT"
minecraft = "1.21.1"

# Gradle Plugins
paperweight = "1.7.1"
runPaper = "2.3.0"
shadow = "8.3.0"

# Bukkit Plugins
placeholderapi = "2.11.6"

# Libraries
packetevents = "2.4.0"
adventure = "4.17.0"
yardwatch = "2.0.0"
hikari = "4.0.3"
vital = "2.8.3"

[libraries]
# Servers
paper = { module = "io.papermc.paper:paper-api", version.ref = "paper" }

# Kyori
kyori-logger = { module = "net.kyori:adventure-text-logger-slf4j", version.ref = "adventure" }
kyori-text = { module = "net.kyori:adventure-text-minimessage", version.ref = "adventure" }
kyori-api = { module = "net.kyori:adventure-api", version.ref = "adventure" }

# Bukkit Plugins
packet-events = { module = "com.github.retrooper:packetevents-spigot", version.ref = "packetevents" }
yardwatch = { module = "com.github.YouHaveTrouble:YardWatchAPI", version.ref = "yardwatch" }
placeholderapi = { module = "me.clip:placeholderapi", version.ref = "placeholderapi" }

# Common
vital-common = { module = "com.ryderbelserion.vital:common", version.ref = "vital" }
vital-paper = { module = "com.ryderbelserion.vital:paper", version.ref = "vital" }
hikari-cp = { module = "com.zaxxer:HikariCP", version.ref = "hikari" }

[bundles]
adventure = [ "kyori-api", "kyori-text", "kyori-logger" ]